export const perceptionSourceCommit = "d85758c752e6cd3244e16d9ea4a3d2831da225b4";
export const perceptionCommands = {
  "01-environment": "python3.11 -m venv .venv-perception\nsource .venv-perception/bin/activate\npython -m pip install --upgrade pip\npython -m pip install torch==2.10.0 torchvision==0.25.0 --index-url https://download.pytorch.org/whl/cpu\npython -m pip install -r perception/generation/requirements.txt\npython -c 'import torch, torchvision, blenderproc, bpy, ultralytics; print(torch.__version__, torchvision.__version__, ultralytics.__version__, bpy.app.version_string)'",
  "02-assets": "cd perception/generation\npython prepare_assets.py --out datasets/fruit_textures/public_fruits360_256 --per-class 256\npython scripts/make_polyhedron_objs.py --out assets/generated --size 0.08",
  "03-render": "python scripts/run_yolo_parallel.py \\\n  --num_images 120 --workers 1 --worker_start_delay 0 \\\n  --asset_dir assets/generated \\\n  --fruit_texture_dir datasets/fruit_textures/public_fruits360_256 \\\n  --background_dir datasets/backgrounds/unused \\\n  --arena_background_ratio 1.0 --output datasets/smoke120 \\\n  --width 640 --height 640 --samples 4 --cpu_threads 1 \\\n  --seed 31000000 --min_objects 1 --max_objects 4 \\\n  --scale_min 0.40 --scale_max 2.45 --negative_ratio 0.18 \\\n  --label_format segment --seg_contour_mode largest \\\n  --seg_contour_epsilon_ratio 0.01 --lighting_mode soft_overhead \\\n  --fruit_texture_aug strong --fruit_texture_layout mixed \\\n  --fruit_texture_collage_prob 0.35 --canonical_fruit_textures \\\n  --allow_mixed_fruit_classes_per_image --allow_multiple_fruit_textures_per_cube \\\n  --ideal_visibility --ideal_visibility_max_attempts 80 --meta_v2 --render_device cpu",
  "04-split": "python scripts/split_meta_v2_dataset.py \\\n  --dataset datasets/smoke120 \\\n  --out datasets/smoke120/split.json --seed 20261006 \\\n  --val-ratio 0.10 --test-ratio 0.10",
  "05-export": "python scripts/export_meta_v2_model_datasets.py \\\n  --source_dataset datasets/smoke120 \\\n  --output_root datasets/smoke120_models \\\n  --split_manifest datasets/smoke120/split.json \\\n  --splits train --tasks a1 --copy_mode hardlink --reset\n\npython scripts/export_meta_v2_cube_face_unified_dataset.py \\\n  --source_dataset datasets/smoke120 \\\n  --output_root datasets/smoke120_face \\\n  --source_split train \\\n  --split_manifest datasets/smoke120/split.json \\\n  --seed 20261006 --crop_size 224 --crop_pad 0.18 --reset",
  "06-train": "python ../training/train_segmentation.py \\\n  --task a1 \\\n  --data datasets/smoke120_models/a1_objectseg/data.yaml \\\n  --init yolo26s-seg.yaml --epochs 1 --batch 4 --workers 0 \\\n  --device cpu --seed 31000000 --lr 0.001 \\\n  --project ../../runs/perception --name smoke120_a1\n\npython ../training/train_segmentation.py \\\n  --task face \\\n  --data datasets/smoke120_face/data.yaml \\\n  --init yolo26s-seg.yaml --epochs 1 --batch 4 --workers 0 \\\n  --device cpu --seed 31000000 --lr 0.001 --hsv-h 0 \\\n  --project ../../runs/perception --name smoke120_face",
  "07-evaluate": "cd ../..\nyolo segment val model=runs/perception/smoke120_a1/weights/best.pt data=perception/generation/datasets/smoke120_models/a1_objectseg/data.yaml imgsz=640 split=test device=cpu\nyolo segment val model=runs/perception/smoke120_face/weights/best.pt data=perception/generation/datasets/smoke120_face/data.yaml imgsz=224 split=test device=cpu"
};
